src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $coverPath = null;

    #[ORM\Column]
    private ?int $priceInCents = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCoverPath(): ?string
    {
        return $this->coverPath;
    }

    public function setCoverPath(?string $coverPath): static
    {
        $this->coverPath = $coverPath;

        return $this;
    }

    public function getPriceInCents(): ?int
    {
        return $this->priceInCents;
    }

    public function setPriceInCents(int $priceInCents): static
    {
        $this->priceInCents = $priceInCents;

        return $this;
    }

    public function getFormatPrice(): string
    {
        return 'R$' . number_format($this->getPriceInCents() / 100, 2, ',', '.');
    }

    public function getPriceInReals(): float
    {
        return $this->getPriceInCents() / 100;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\CartItem;
use App\Services\CartService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[IsGranted('ROLE_USER')]
class CartController extends AbstractController
{
    public function __construct(private CartService $cart, private EntityManagerInterface $entityManager)
    {
    }

    #[Route('/cart', name: 'app_cart')]
    public function index(): Response
    {
        $items = $this->cart->getBooks($this->getUser());

        $total = array_reduce($items, fn ($acumuled, CartItem $value) => $acumuled + $value->getBook()->getPriceInCents(), 0);
        $total = 'R$' . number_format($total / 100, 2, ',', '.');

        return $this->render('cart/index.html.twig', compact('items', 'total'));
    }

    #[Route('/cart/add/{book}', name: 'app_cart_add', methods: ["POST"])]
    public function addBook(Book $book): Response
    {
        $this->cart->addBook($this->getUser(), $book);

        $this->addFlash('success', 'Livro adicionado ao carrinho');

        return $this->redirectToRoute('app_book_show', ['id' => $book->getId()]);
    }

    #[Route('/cart/remove/{id}', name: 'app_cart_remove', methods: ['POST'])]
    public function remove(int $id): Response
    {
        $item = $this->entityManager->getReference(CartItem::class, $id);
        $this->entityManager->remove($item);
        $this->entityManager->flush();

        $this->addFlash('success', 'Livro removido do carrinho');

        return $this->redirectToRoute('app_cart');
    }

    #[Route('/cart/book/remove/{book}', name: 'app_cart_remove_book', methods: ["POST"])]
    public function removeBook(Book $book): Response
    {
        $this->cart->removeBook($this->getUser(), $book);

        $this->addFlash('success', 'Livro removido do carrinho');

        return $this->redirectToRoute('app_book_show', ['id' => $book->getId()]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carrinho{% endblock %}

{% block body %}

<ul class="my-4 list-group">
    {% for item in items %}
        <li class="list-group-item d-flex align-items-center justify-content-between">
            <div class="m-2">
                <a href="{{ path("app_book_show", {id: item.book.id}) }}" class="fs-5">{{ item.book.title }}</a>
                <p class="fs-5 m-0">{{  item.book.formatPrice }}</p>
            </div>

            <form action="{{ path('app_cart_remove', {id: item.id}) }}" method="POST">
                <button class="btn btn-danger">Remover do carrinho</button>
            </form>
        </li>
    {% endfor %}
</ul>

<h3>Total: {{ total }}</h3>
<div class="mt-3">
    <a href="#" class="btn btn-success me-2">Realizar compra</a>
    <a href="{{ path('app_book_index') }}" class="btn btn-secondary">Voltar</a>
</div>

{% endblock %}